/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      borderColor: {
        DEFAULT: 'rgb(var(--color-wolf) / <alpha-value>)',
      },
      screens: {
        xs: '375px',
        '3xl': '1920px',
        '4k': '2560px',
        tv: '3840px',
      },
      container: {
        center: true,
        padding: {
          DEFAULT: '1rem',
          sm: '1.25rem',
          md: '1.5rem',
          lg: '2rem',
          xl: '3rem',
          '2xl': '4rem',
        },
      },
      spacing: {
        'safe-bottom': 'env(safe-area-inset-bottom, 0px)',
        'safe-top': 'env(safe-area-inset-top, 0px)',
        'safe-left': 'env(safe-area-inset-left, 0px)',
        'safe-right': 'env(safe-area-inset-right, 0px)',
      },
      minHeight: {
        touch: '44px',
      },
      minWidth: {
        touch: '44px',
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
        '3xs': ['0.5rem', { lineHeight: '0.75rem' }],
      },
      colors: {
        background: 'rgb(var(--color-eel) / <alpha-value>)',
        sidebar: 'rgb(var(--color-snow-always-light) / <alpha-value>)',
        surface: 'rgb(var(--color-snow-always-light) / <alpha-value>)',
        'surface-hover': 'rgb(var(--color-wolf) / <alpha-value>)',
        'surface-alt': 'rgb(var(--color-anchovy) / <alpha-value>)',
        'surface-active': 'rgb(var(--color-swan-always-light) / <alpha-value>)',
        text: 'rgb(var(--color-snow) / <alpha-value>)',
        'text-muted': 'rgb(var(--color-swan) / <alpha-value>)',
        'text-dim': 'rgb(var(--color-hare) / <alpha-value>)',
        border: 'rgb(var(--color-wolf) / <alpha-value>)',
        'border-hover': 'rgb(var(--color-hare) / <alpha-value>)',
        white: 'rgb(255 255 255 / <alpha-value>)',
        'white-always': 'rgb(255 255 255 / <alpha-value>)',
        'snow-dark': 'rgb(var(--color-snow) / <alpha-value>)',
        primary: '#555555',
        'primary-hover': '#444444',
        'primary-dark': '#333333',
        'primary-light': '#777777',
        secondary: '#1A1A1A',
        reward: '#AAAAAA',
        'reward-soft': '#DDDDDD',
        accent: '#777777',
        'accent-dark': '#555555',
        flame: '#888888',
        'flame-mid': '#999999',
        'flame-light': '#BBBBBB',
        cardinal: '#666666',
        'cardinal-dark': '#444444',
        macaw: '#AAAAAA',
        starling: '#777777',
        betta: '#888888',
        peacock: '#777777',
        owl: '#555555',
        treefrog: '#444444',
        turtle: '#333333',
        crimson: '#444444',
        charcoal: '#1A1A1A',
        wolf: '#E0E0E0',
        eel: '#F0F0F0',
        hare: '#B0B0B0',
        swan: '#888888',
        snow: '#1A1A1A',
      },
      fontFamily: {
        sans: ['Nunito Sans', 'Hind Siliguri', 'Noto Sans Bengali', 'system-ui', 'sans-serif'],
      },
      animation: {
        'pulse-soft': 'pulse 3s ease-in-out infinite',
        'bounce-in': 'bounceIn 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'shake': 'shake 0.4s ease-in-out',
        'float-up': 'floatUp 0.8s ease-out forwards',
        'scale-in': 'scaleIn 0.2s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        bounceIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-8px)' },
          '40%': { transform: 'translateX(8px)' },
          '60%': { transform: 'translateX(-5px)' },
          '80%': { transform: 'translateX(5px)' },
        },
        floatUp: {
          '0%': { transform: 'translateY(0)', opacity: '1' },
          '100%': { transform: 'translateY(-40px)', opacity: '0' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
